### ISSUE TITLE
Please re-create this repo by forking from https://github.com/yandex/ClickHouse

### ISSUE THREAD

**Issue by proller** [jbfavre/clickhouse-debian#1]
Now very hard to track changes.
Also some parts related to debian package already was changed (like server postinst).

Also please dont forget change user/group from metrika:metrika to clickhouse:clickhouse

**Comment by jbfavre** [comment]
You still can track changes if you fork/clone this repo, add upstream clickhouse repo as remote with `git remote add upstream https://github.com/yandex/ClickHouse.git`.

Changes can be seen with `git diff master upstream/master debian`.

While I'm not that confortable with it, I'll have a look on maintaining debianization in a specific branch of clickhouse repo after forking it.
For example postinst changes, I only import stable release (see `debian/watch`) so daily changes are likely to not be included.

**Comment by jbfavre** [comment]
You can find the latest Debian packaging version here: https://github.com/jbfavre/ClickHouse/tree/debian

**Comment by proller** [comment]
Thank you, now diff much easier: https://github.com/yandex/ClickHouse/compare/master...jbfavre:debian
